config/urls.py
"""config URL Configuration"""

# Libraries
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

# Base Views
from .views import home_view

urlpatterns = [
    path('', home_view),
    path('admin/', admin.site.urls),
    path('clients/', include(('src.clients.urls', 'clients'), namespace='clients')),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

src/clients/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from src.clients import views


urlpatterns = [
    # Management
    path(
        route='',
        view=views.ClientListView.as_view(),
        name='list'
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),

    # User
    path(
        route='<str:username>/',
        view=views.ClientDetailView.as_view(),
        name='detail'
    ),
    path(
        route='<str:username>/edit/',
        view=views.ClientEditView.as_view(),
        name='edit'
    )
]

src/clients/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='clients/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

src/clients/models/profiles.py
"""
Profile Model
"""

# Django
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(
        'clients.User',
        on_delete=models.CASCADE
    )

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='clients/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return str(self.user)

src/clients/models/users.py
"""
Base Django Configuration
"""

# Django
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models

# Utilities
from src.utils.models import AbstractModel


class User(AbstractModel, AbstractUser):
    """User Model"""
    email = models.EmailField(
        'email address',
        unique=True,
        error_messages={
            'unique': 'A user with that email already exists.'
        }
    )

    phone_regex = RegexValidator(
        regex=r'\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: +999999999. Up to 15 digits allowed."
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    is_client = models.BooleanField(
        'client',
        default=True,
        help_text=(
            'Help easily distinguish users and perform queries. '
            'Clients are the main type of user.'
        )
    )

    is_verified = models.BooleanField(
        'verified',
        default=True,
        help_text='Set to true when the user have verified its email address.'
    )

    def __str__(self):
        """Return username."""
        return self.username

    def get_short_name(self):
        """Return username."""
        return self.username

src/utils/models.py
"""Django Models utils"""

# Django User
from django.db import models


class AbstractModel(models.Model):
    """
    Share Abstract Model
    """
    created = models.DateTimeField(
        'created at',
        auto_now_add=True,
        help_text='Date time on which the object was created.'
    )
    modified = models.DateTimeField(
        'modified at',
        auto_now=True,
        help_text='Date time on which the object was last modified.'
    )

    class Meta:
        """Meta option."""

        abstract = True

        get_latest_by = 'created'
        ordering = ['-created', '-modified']

src/clients/forms.py
"""User forms."""

# Django
from django import forms

# Models
from src.clients.models import User
from src.clients.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean_email(self):
        """Email must be unique"""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()


class ExtendClientEditForm(forms.Form):
    """Form Extend"""
    picture = forms.ImageField(
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )
    phone_number = forms.CharField(
        min_length=7,
        max_length=17,
    )
    website = forms.CharField(
        max_length=200,
    )
    biography = forms.CharField(
        max_length=400,
        widget=forms.TextInput
    )
    first_name = forms.CharField(
        min_length=3,
        max_length=25,
    )
    last_name = forms.CharField(
        min_length=3,
        max_length=25,
    )

    def save(self):
        """Update the data"""
        print('data')

src/clients/views.py
"""Module for views"""

# Libraries
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, FormView, UpdateView
from django.views.generic.list import ListView

# Forms
from src.clients.forms import (
    SignupForm,
    ExtendClientEditForm,
)

# Models Clients and User
from src.clients.models import (
    Profile,
    User,
)


class ClientDetailView(LoginRequiredMixin, DetailView):
    """user detail view."""
    template_name = 'clients/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'client'


class ClientEditView(LoginRequiredMixin, UpdateView):
    """Client Edit View"""
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']
    template_name = 'clients/edit.html'
    success_url = reverse_lazy('clients:list')

    def get_object(self) -> Profile:
        """Get object for get obj based into User"""
        user = User.objects.get(username=self.kwargs['username'])
        return self.model.objects.get(user=user)


class LoginView(auth_views.LoginView):
    """login view."""
    template_name = 'clients/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """logout view."""
    template_name = 'clients/logged_out.html'


class SignupView(FormView):
    """Users sign up view."""
    template_name = 'clients/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('clients:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    """List of Clients"""
    template_name = 'clients/list.html'
    model = Profile
    paginate_by = 100

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block head_content %}{% endblock %}


    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

  </head>
  <body>

    {% include "nav.html" %}

    <div class="wrapper">
      {% include "sidebar.html" %}

      <div class="content content-main">
        <div id="content">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
          </nav>
        </div>

        <div class="container mt-5">
          {% block container %}
          {% endblock%}
        </div>
      </div>

    </div>

    <footer>
      <p>
        Client Base - Project - Gabriel Vargas
      </p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="{% static 'javascript/main.js' %}"></script>
  </body>
</html>

src/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>Control Client</title>

<style>
 .control {
   max-width: 100%;
   height: 445px;
   background-image: url("{% static 'imgs/morfeo.jpeg' %}");
   justify-content: center;
   display: flex;
   background-position: 50% 50%;
 }
</style>
{% endblock%}

{% block container %}
<div class="container control">
  <div class="row align-items-end">
    <div class="col">
      <h1 class="display-1 text-center main-title">
        {% if user and user.is_authenticated %}
        You're a Slave {{ user.username|title }}
        {% else %}
        You're Slave Neo
        {% endif %}
      </h1>
    </div>
  </div>
</div>

<div class="container">
  <h1 class="text-center">Choose The Pills</h1>
  <div class="row">
    <a href="/red" class="col align-self-center" style="display: flex; justify-content: center;">
      <i class="fas fa-pills text-center" style="font-size: 120px; color: red"></i>
    </a>
    <a href="/blue" class="col align-self-center" style="display: flex; justify-content: center;">
      <i class="fas fa-pills text-center" style="font-size: 120px; color: blue"></i>
    </a>
  </div>
</div>
{% endblock%}

src/templates/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a href="{% url 'clients:list' %}" class="navbar-brand">
      <img src="{% static "imgs/instagram.png" %}" height="45" class="d-inline-block align-top"/>
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarContent" style="justify-content: flex-end;">
      <ul class="navbar-nav">
        {% if user and user.is_authenticated %}
        <li class="nav-item" style="padding-top: 8.75px;padding-bottom: 8.75px;">
          <a href="{% url 'clients:detail' user.username %}">
            {% if user.profile.picture %}
            <img src="{{ user.profile.picture.url }}" alt="icon user" height="35">
            {% else %}
            <img src="{% static 'imgs/default-profile.png' %}" alt="icon user" height="35"/>
            {% endif %}
          </a>
        </li>
        <li class="nav-item">
          <li class="nav-item" style="font-size: 35px;">
            <a href="{% url 'clients:logout' %}">
              <i class="fas fa-sign-out-alt"></i>
            </a>
          </li>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'clients:signup' %}">
            <p>SignUp</p>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'clients:login' %}">
            <p>Login</p>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

src/templates/sidebar.html
<nav id="sidebar" class="sidebar sidebar-active">

  <div class="table-responsive">
    <table class="menu-links">
      <thead>
        <th></th>
      </thead>
      <tbody id="items-menu">
        <tr class="item-menu">
          <td>
            <div class="linear">
              <i class="fas fa-users" style="font-size: 20px;"></i>
              <p>
                Clients
              </p>
            </div>
          </td>
        </tr>
        <tr class="item-menu">
          <td>
            <div class="linear">
              <i class="fas fa-users" style="font-size: 20px;"></i>
              <p>
                Clients
              </p>
            </div>
          </td>
        </tr>
        <tr class="item-menu">
          <td>
            <div class="linear">
              <i class="fas fa-users" style="font-size: 20px;"></i>
              <p>
                Clients
              </p>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div>
    <button
      type="button"
      class="btn btn-primary"
      id="sidebarCollapse"
      onclick="activateSidebar()"
    >
      <i class="fas fa-archive" style="font-size: 35px;"></i>
      Client Base
    </button>
  </div>
</nav>