config/urls.py
"""config URL Configuration"""

# Libraries
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

# Base Views
from .views import home_view

urlpatterns = [
    path('', home_view),
    path('admin/', admin.site.urls),
    path('clients/', include(('src.clients.urls', 'clients'), namespace='clients')),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

src/clients/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from src.clients import views


urlpatterns = [
    # Management
    path(
        route='',
        view=views.ClientListView.as_view(),
        name='list'
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),

    # User
    path(
        route='<str:username>/',
        view=views.ClientDetailView.as_view(),
        name='detail'
    ),
    path(
        route='<str:username>/edit/',
        view=views.ClientEditView.as_view(),
        name='edit'
    )
]

src/clients/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='clients/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

src/clients/models/profiles.py
"""
Profile Model
"""

# Django
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(
        'clients.User',
        on_delete=models.CASCADE
    )

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='clients/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return str(self.user)

src/clients/models/users.py
"""
Base Django Configuration
"""

# Django
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models

# Utilities
from src.utils.models import AbstractModel


class User(AbstractModel, AbstractUser):
    """User Model"""
    email = models.EmailField(
        'email address',
        unique=True,
        error_messages={
            'unique': 'A user with that email already exists.'
        }
    )

    phone_regex = RegexValidator(
        regex=r'\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: +999999999. Up to 15 digits allowed."
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    is_client = models.BooleanField(
        'client',
        default=True,
        help_text=(
            'Help easily distinguish users and perform queries. '
            'Clients are the main type of user.'
        )
    )

    is_verified = models.BooleanField(
        'verified',
        default=True,
        help_text='Set to true when the user have verified its email address.'
    )

    def __str__(self):
        """Return username."""
        return self.username

    def get_short_name(self):
        """Return username."""
        return self.username

src/utils/models.py
"""Django Models utils"""

# Django User
from django.db import models


class AbstractModel(models.Model):
    """
    Share Abstract Model
    """
    created = models.DateTimeField(
        'created at',
        auto_now_add=True,
        help_text='Date time on which the object was created.'
    )
    modified = models.DateTimeField(
        'modified at',
        auto_now=True,
        help_text='Date time on which the object was last modified.'
    )

    class Meta:
        """Meta option."""

        abstract = True

        get_latest_by = 'created'
        ordering = ['-created', '-modified']

src/clients/forms.py
"""User forms."""

# Django
from django import forms

# Models
from src.clients.models import User
from src.clients.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean_email(self):
        """Email must be unique"""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()


class ExtendClientEditForm(forms.Form):
    """Form Extend"""
    picture = forms.ImageField(
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )
    phone_number = forms.CharField(
        min_length=7,
        max_length=17,
    )
    website = forms.CharField(
        max_length=200,
    )
    biography = forms.CharField(
        max_length=400,
        widget=forms.TextInput
    )
    first_name = forms.CharField(
        min_length=3,
        max_length=25,
    )
    last_name = forms.CharField(
        min_length=3,
        max_length=25,
    )

    def save(self):
        """Update the data"""
        print('data')

src/clients/views.py
"""Module for views"""

# Libraries
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, FormView, UpdateView
from django.views.generic.list import ListView

# Forms
from src.clients.forms import (
    SignupForm,
    ExtendClientEditForm,
)

# Models Clients and User
from src.clients.models import (
    Profile,
    User,
)


class ClientDetailView(LoginRequiredMixin, DetailView):
    """user detail view."""
    template_name = 'clients/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'client'


class ClientEditView(LoginRequiredMixin, UpdateView):
    """Client Edit View"""
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']
    template_name = 'clients/edit.html'
    success_url = reverse_lazy('clients:list')

    def get_object(self) -> Profile:
        """Get object for get obj based into User"""
        user = User.objects.get(username=self.kwargs['username'])
        return self.model.objects.get(user=user)


class LoginView(auth_views.LoginView):
    """login view."""
    template_name = 'clients/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """logout view."""
    template_name = 'clients/logged_out.html'


class SignupView(FormView):
    """Users sign up view."""
    template_name = 'clients/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('clients:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    """List of Clients"""
    template_name = 'clients/list.html'
    model = Profile
    paginate_by = 100

src/templates/clients/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head_content %}
    {% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

  </head>
  <body class="h-100">

    <div class="container h-100">
      <div class="row h-100 justify-content-center align-items-center">
        <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

          <img src="{% static 'imgs/instagram.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

          {% block container %}{% endblock%}

        </div>
      </div>
    </div>

    <script src="{% static 'javascript/main.js' %}"></script>
  </body>
</html>

src/templates/clients/detail.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ user.username }} | Details</title>
{% endblock %}

{% block container %}
<div class="container">
  <div class="text-center">
    <h1>Details of @{{client.username}}</h1>
    {% if user == object or user.is_staff or user.is_superuser %}
    <a
      href="{% url 'clients:edit' username=client.username %}"
      class="btn btn-outline-primary"
    >
      Edit User
    </a>
    {% endif %}
  </div>

  <hr/>
  <div class="container">

    <div class="img">
      {% if client and client.profile.picture %}
      <img src="{{ client.profile.picture.url }}" alt="icon user" height="200">
      {% else %}
      <img src="{% static 'imgs/default-profile.png' %}" alt="image" height="200"/>
      {% endif %}
    </div>

    <div class="justify-content-center">
      <h5 class="col-12">Active:</h5>
      <p class="col-12">
        {% if client.is_active %}
        <i class="fas fa-check-circle"></i>
        {% else %}
        <i class="fas fa-times-circle"></i>
        {% endif %}
      </p>
    </div>

    <div class="justify-content-center">
      <h5 class="col-12">Name:</h5>
      <p class="col-12">
        {{ client.first_name }}
      </p>
    </div>

    <div class="justify-content-center">
      <h5 class="col-12">Last Name:</h5>
      <p class="col-12">
        {{ client.last_name }}
      </p>
    </div>

    <div class="justify-content-center">
      <h5 class="col-12">Phone:</h5>
      <p class="col-12">
        {{ client.profile.phone_number }}
      </p>
    </div>

    <div class="justify-content-center">
      <h5 class="col-12">Website:</h5>
      <p class="col-12">
        {{ client.profile.website }}
      </p>
    </div>

    <div class="justify-content-center">
      <h5 class="col-12">Biography:</h5>
      <p class="col-12">
        {{ client.profile.biography }}
      </p>
    </div>

    <div class="justify-content-center">
      <h5 class="col-12">Created:</h5>
      <p class="col-12">
        {{ client.profile.created }}
      </p>
    </div>

    <div class="justify-content-center">
      <h5 class="col-12">Verified:</h5>
      <p class="col-12">
        {% if client.is_verified %}
        <i class="fas fa-check-circle"></i>
        {% else %}
        <i class="fas fa-times-circle"></i>
        {% endif %}
      </p>
    </div>

    <div class="justify-content-center">
      <h5 class="col-12">Client:</h5>
      <p class="col-12">
        {% if client.is_client %}
        <i class="fas fa-check-circle"></i>
        {% else %}
        <i class="fas fa-times-circle"></i>
        {% endif %}
      </p>
    </div>

    {% if object == client or client.is_staff or client.is_superuser %}
    <div class="justify-content-center">
      <h5 class="col-12">Email:</h5>
      <p class="col-12">
        {{ client.email }}
      </p>
    </div>

    {% endif %}

    {% if client.is_staff or client.is_superuser %}
    <div class="justify-content-center">
      <h5 class="col-12">Is Staff:</h5>
      <p class="col-12">
        {% if client.is_staff %}
        <i class="fas fa-check-circle"></i>
        {% else %}
        <i class="fas fa-times-circle"></i>
        {% endif %}
      </p>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

src/templates/clients/edit.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ user.username }} | Edit</title>
{% endblock%}

{% block container %}

<div class="container">
  <h1>Edit @{{ user.username }}</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
  </form>
</div>

{% endblock %}

src/templates/clients/list.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ user.username }} | List Of Users</title>
{% endblock %}

{% block container %}
<h1>List of Clients</h1>
<div class="table-responsive">
  <table class="table table-striped caption-top">
  <caption>Clients Available: {{object_list.count}}</caption>
  <thead>
    <tr>
      <th scope="col">Picture</th>
      <th scope="col">Username</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Is Client</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <th scope="row">
        <a href="{% url 'clients:detail' object.user.username %}">
          <img
            alt="icon user {{object.user.username}}"
            src="{%if object.picture %}{{ object.picture.url }}{% else %}{% static 'imgs/default-profile.png' %}{% endif %}"
            height="35"
          />
        </a>
      </th>
      <td>{{ object.user.username }}</td>
      <td>{{ object.user.first_name }}</td>
      <td>{{ object.user.last_name }}</td>
      <td>
        {% if client.is_client %}
        <i class="fas fa-check-circle"></i>
        {% else %}
        <i class="fas fa-times-circle"></i>
        {% endif %}
      </td>
      <td>
        <a href="{% url 'clients:detail' object.user.username %}">
          <i class="fas fa-eye">
          </i>
          {% if user.is_staff or user.is_superuser %}
          <i class="fas fa-edit">
          </i>
          {% endif %}
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
  </table>
</div>
{% endblock %}

src/templates/clients/login.html
{% extends "clients/base.html" %}

{% block head_content %}
<title>Sign Up</title>
{% endblock%}

{% block container %}

{% if form.errors %}
<p class="alert alert-danger">
  Your username and password didn't match. Please try again.
</p>
{% endif%}

<form method="POST" action="{% url "clients:login" %}">
  {% csrf_token %}

  <div class="form-group">
    <input class="form-control" type="text" placeholder="Email" name="username" />
  </div>

  <div class="form-group">
    <input class="form-control" type="password" placeholder="Password" name="password" />
  </div>


  <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>

</form>

<p class="mt-4">Don't have an account yet? <a href="{% url "clients:signup" %}">Sign up here.</a></p>

{% endblock %}

src/templates/clients/signup.html
{% extends "clients/base.html" %}

{% block head_content %}
<title>sign up</title>
{% endblock %}

{% block container %}

<form action="{% url 'clients:signup' %}" method="POST">
  {% csrf_token %}

  {{ form.as_p }}

  <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

</form>

{% endblock %}